title: "Fred Phillips"
url: "https://fred.codes"
github_username: fophillips
description: "Fred Phillips's Blog"
github: [metadata]
remote_theme: fophillips/no-style-please
theme_config:
  appearance: "dark"
  back_home_text: ".."
  date_format: "%Y-%m-%d"
include:
  - _posts
plugins:
  - jekyll-feed
  - jekyll-seo-tag
